### PR TITLE
Cache CG coefficients

### PR DESCRIPTION
**Pull request by olivier-peltre**
Right now, Clebsch-Gordan coefficients are recomputed at every tensor product call. 
This means they are also recomputed e.g. every time N scalars are used to gate N irreps with `IrrepsArray.__mul__`, as it calls `elementwise_tensor_product`, i.e. at every MACE message-passing step, symmetric contraction step, etc. 

The torch version of e3nn wraps CG coefs in functools.cache:
https://github.com/e3nn/e3nn/blob/ac3528f7fb5fe1a8838f1df087d2eefe60d91ea8/e3nn/o3/_wigner.py#L149

NB `functools.lru_cache(maxsize=None)` is an alias for `functools.cache` 

NB it might also be more efficient to use a dense/spare array format than relying on a generic hashtable

### CODE REVIEW

**Comment by mariogeiger** [comment]
The anger of `@functools.cache` is the following

```python
@functools.cache
def f(n: int) -> np.ndarray:
    return np.array(n)


x = f(1)
x += 41
print(f(1))  
# prints 42
```

This is why I did not cache the function.
Now that I think about it we can protect it like that:
```python
@functools.cache
def _f(n: int) -> np.ndarray:
    return np.array(n)


def f(n: int) -> np.ndarray:
    return _f(n).copy()


x = f(1)
x += 41
print(f(1))
# prints 1
```

Please do something like that

**Comment by olivier-peltre** [comment]
I'm not sure to understand why you would ever want to perform in-place operations on tabulated constants like CG coefficients :thinking:

**Comment by mariogeiger** [comment]
This can happen accidentally. It happened to me on the pytorch version of e3nn and that's why I did cache this code

**Comment by mitkotak** [comment]
I am also getting stalled by the CG computing code on the CPU when running lmax > 11. 

My work around is by explicitly calling coefficients cached in an `.npz` file. I am calling and creating the file using [BasisLib](https://github.com/atomicarchitects/BasisLib). ([Dependencies](https://github.com/atomicarchitects/BasisLib/blob/c93f028aeca6bcde38e709d3c12be99190485b84/pyproject.toml#L27-L33) are Numpy and friends).

Interface looks something like [this](https://github.com/mitkotak/e3nn-jax/blob/basislib/e3nn_jax/_src/so3.py#L41-L53). 
```python
e3nn_jax.clebsch_gordan_basislib(l1, l2, l3)
```
Can put in PR if it makes sense ? @mariogeiger

**Comment by mariogeiger** [comment]
Either we completely switch to BasisLib or we keep it local. Why having two different implementations of the same thing?

**Comment by mariogeiger** [comment]
Btw I'm waiting for the copy safe cache and we can already merge this

**Comment by mitkotak** [comment]
@mariogeiger Is this what you meant ? https://github.com/mitkotak/e3nn-jax/pull/1

**Comment by mariogeiger** [comment]
I mean what I said in my fist comment. We need to systematically copy the cached data to avoid it getting modified inplace by accident. This causes bug what are extremely hard to debug.

**Comment by mitkotak** [comment]
@mitkotak Sorry seems like my push did not update Github before. I have the safe copy thing that you were requesting.

**Comment by mariogeiger** [comment]
I don't see any changes

**Comment by mitkotak** [comment]
Sorry for the confusion. Can you see (this)[https://github.com/mitkotak/e3nn-jax/pull/1/files] ?

**Comment by mariogeiger** [comment]
This this is a PR in your own fork repo

**Comment by mitkotak** [comment]
Did not have write permissions to this one

**Comment by mariogeiger** [comment]
I guess it's because we are on @olivier-peltre own branch. 

Maybe you can create a new PR but this time select this repo as a target, not your own fork.

**Pull request closed without merging**
