### PR TITLE
Add installation instructions and requirements.txt

### PR DESCRIPTION
**Pull request by ameya98**

### CODE REVIEW

**Comment by mariogeiger** [comment]
Do you know if setup.py takes into account requirements.txt ?

**Comment by ameya98** [comment]
Good question! It does not. I found [this recommendation](https://caremad.io/posts/2013/07/setup-vs-requirement/) to avoid duplication of package names.

**Comment by ameya98** [comment]
Since the `chex` import is currently broken because of a recent commit, I have manually specified installation of `chex` from their GitHub repo.

**Comment by ameya98** [comment]
This should address #12

**Pull request merged**
