### PR TITLE
Refactore core_tensor_product.py

### PR DESCRIPTION
**Pull request by ameya98**

### CODE REVIEW

**Comment by mariogeiger** [comment]
I like the `Instruction` class you created!!
I also like that the normalization is done in a separate function.
Would it be possible to write `normalize_instruction_path_weights` in a slightly simpler form? It looks a bit long and circumvoluted right now

**Comment by ameya98** [comment]
Thanks! Is this better now?

**Comment by mariogeiger** [comment]
What do you think about that?
In the compromise between modularity (a lot of functions) and simplicity (less functions) I removed one function

**Comment by ameya98** [comment]
Hmm, I’m not a big fan of creating the intermediate ‘fn’ variable only to call it in the next few lines. However, I will leave it up to you to make the final call :)

**Comment by mariogeiger** [comment]
Fair point! I also don't like when variables are created to used just once

**Pull request merged**
